// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xdma_filter.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XDma_filter_CfgInitialize(XDma_filter *InstancePtr, XDma_filter_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XDma_filter_Set_minAddress(XDma_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDma_filter_WriteReg(InstancePtr->Axilites_BaseAddress, XDMA_FILTER_AXILITES_ADDR_MINADDRESS_DATA, Data);
}

u32 XDma_filter_Get_minAddress(XDma_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDma_filter_ReadReg(InstancePtr->Axilites_BaseAddress, XDMA_FILTER_AXILITES_ADDR_MINADDRESS_DATA);
    return Data;
}

